
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_gx_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_gx_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  load_date: '1992-01-08'
  tpch_size: 10 #1, 10, 100, 1000, 10000

  'dbt_date:time_zone': 'America/Chicago'
  my_ref: 'ref'

models:
  dbt_gx_demo:
    # Config indicated by + and applies to all files under models/example/
    bronze:
      audit:
        schema: audit
        tags:
          - 'audit'
        raw_stage:
          +materialized: table
        raw_vault:
          +materialized: table
        stage:
          +pre-hook: "{{ project_governance_check() }}"
          +materialized: view
          tags:
            - "governance"
        flight_demo:
          tags:
            - 'flight_demo'
        sales_demo:
          tags:
            - 'sales_demo'
            - 'stage_sales_demo'
      demo_build:
        schema: raw
        +materialized: table
        tags:
          - 'demo_build'
      processed:
        +pre-hook: "{{ project_governance_check() }}"
        schema: processed
        +materialized: table
        tags:
          - 'processed'
        flight_demo:
          tags:
            - 'flight_demo'
        netflix_demo:
          tags:
            - 'netflix_demo'
        sales_demo:
          tags:
            - 'sales_demo'
            - 'processed_sales_demo'
      raw:
        schema: raw
        +materialized: table
        tags:
          - 'raw'
        flight_demo:
          tags:
            - 'flight_demo'
        netflix_demo:
          tags:
            - 'netflix_demo'
        sales_demo:
          tags:
            - 'sales_demo'
      staging:
        +pre-hook: "{{ project_governance_check() }}"
        schema: stage
        +materialized: table
        tags:
          - 'staging'
        flight_demo:
          tags:
            - 'flight_demo'
        netflix_demo:
          tags:
            - 'netflix_demo'
        sales_demo:
          tags:
            - 'sales_demo'
            - 'staging_sales_demo'
    dbt_artifacts:
      +materialized: view
      +file_format: delta
      +database: BRONZE
      +schema: OBSERVABILITY
      staging:
        +database: BRONZE
        +schema: OBSERVABILITY
      sources:
        +materialized: incremental
        +on_schema_change: append_new_columns
        +full_refresh: false
        +database: BRONZE
        +schema: OBSERVABILITY
    gold:
      +materialized: view
    silver:
      +materialized: view


on-run-end:
  - "{{ snowflake_utils.apply_meta_as_tags(results) }}"
  - "{{ log_dbt_results(results) }}"
  - "{{ dbt_artifacts.upload_results(results) }}"
